development:
    adapter: mysql2
    database: fleetsuite_development
    username: root
    password:
    host: localhost
    encoding: utf8

test:
    adapter: mysql2
    database: fleetsuite_test
    username: root
    password: 
    host: localhost
    encoding: utf8
    
production:
    adapter: mysql2
    database: fleetsuite_production
    username: root
    password:
    host: localhost
    encoding: utf8